#!/usr/bin/env bash
# This script installs NGINX on the machine and
# and makes it return the string "Hello World!"
# when queried with a GET request.
sudo apt update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
